### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by zbx911** [fancidev/qtinter#12]
111

**Comment by zbx911** [comment]
AttributeError: 'HexEditorDialog' object has no attribute 'blockSignals'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_pydevd_frame_eval/pydevd_frame_evaluator_common.pyx", line 150, in _pydevd_frame_eval.pydevd_frame_evaluator_common.get_func_code_info
    func_code_info = FuncCodeInfo()
SystemError: <class '_pydevd_frame_eval.pydevd_frame_evaluator_common.FuncCodeInfo'> returned a result with an error set

**Comment by zbx911** [comment]
AttributeError: 'HexEditorDialog' object has no attribute 'byte'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_pydevd_frame_eval/pydevd_frame_evaluator_common.pyx", line 150, in _pydevd_frame_eval.pydevd_frame_evaluator_common.get_func_code_info
    func_code_info = FuncCodeInfo()
SystemError: <class '_pydevd_frame_eval.pydevd_frame_evaluator_common.FuncCodeInfo'> returned a result with an error set
