### ISSUE TITLE
System test errors

### ISSUE THREAD

**Issue by fancidev** [fancidev/qtinter#6]
Use this issue to record errors in the "system test" step in CI testing. These test failures (except those caused by test infrastructure problem) are used to reveal bugs in the Python standard library itself.

**Comment by fancidev** [comment]
tests #88 had the following error:

[Python-3.7-PySide6-macos-latest](https://github.com/fancidev/qtinter/actions/runs/3177912055/jobs/5178873550)

```
Run python -m test.test_asyncio
  python -m test.test_asyncio
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.7.14/x64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.7.14/x64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.7.14/x64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.7.14/x64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.7.14/x64

...

======================================================================
FAIL: test_run_until_complete (test.test_asyncio.test_events.SelectEventLoopTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/test/test_asyncio/test_events.py", line 272, in test_run_until_complete
    self.assertTrue(0.08 <= t1-t0 <= 0.8, t1-t0)
AssertionError: False is not true : 0.8978740370000011

----------------------------------------------------------------------
Ran 2055 tests in 55.711s

FAILED (failures=1, skipped=37)
Error: Process completed with exit code 1.
```

This looks like a flaw with the test case itself.

**Comment by fancidev** [comment]
tests #94 had the following error:

[Python-3.10-PyQt6-macos-latest](https://github.com/fancidev/qtinter/actions/runs/3197582371/jobs/5220993294)

```
Run python -m test.test_asyncio
  python -m test.test_asyncio
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.10.7/x64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.10.7/x64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.10.7/x64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.10.7/x64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.10.7/x64

...

======================================================================
ERROR: test_create_ssl_connection (test.test_asyncio.test_events.KqueueEventLoopTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/test/test_asyncio/test_events.py", line 642, in test_create_ssl_connection
    self._test_create_ssl_connection(httpd, create_connection,
  File "/Users/runner/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/test/test_asyncio/test_events.py", line 630, in _test_create_ssl_connection
    self._basetest_create_ssl_connection(conn_fut, check_sockname,
  File "/Users/runner/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/test/test_asyncio/test_events.py", line 589, in _basetest_create_ssl_connection
    tr, pr = self.loop.run_until_complete(connection_fut)
  File "/Users/runner/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/runner/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Users/runner/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/Users/runner/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer

----------------------------------------------------------------------
Ran 2268 tests in 69.858s

FAILED (errors=1, skipped=73)
Error: Process completed with exit code 1.
```

This looks like a glitch of the test infrastructure.

**Comment by fancidev** [comment]
There appears to be no *new* type of error apart from the above. Closing this issue for now.
